openapi: '3.0.2'
info:
  title: Agence de voyage
  description: Labo agence de voyage du cours web architecture
  version: '1.0'
servers:
  - url: http://localhost:8080 

paths:
  /destination:
    get:
      summary: List all the destinations
      responses:
        '200':
          description: A JSON array of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["La Clusaz","Annecy"]
    post:
      summary: Add a destination
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: La Clusaz
                  required:
                    - "true"
                description:
                  type: string
                  example: Big Estate Near the Indian Ocean
                  required:
                    - "true"
                country:
                  type: string
                  example: South Africa
                  required:
                    - "true"
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Destination added
  /destination/{destId}:
    get:
      summary: Return a destination description with id or name
      parameters:
        - name: destId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of destination
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                    format: int64
                    example: 42
                  name:
                    type: string
                    example: La Clusaz
                  description:
                    type: string
                    example: Big Estate Near the Indian Ocean
                  country:
                    type: string
                    example: South Africa
    delete:
      summary: Deletes a destination
      parameters:
        - name: destId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Destination deleted
  /searchDestination:
    post:
      summary: search a destination
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 42
                  required:
                    - "false"
                name:
                  type: string
                  example: La Clusaz
                  required:
                    - "false"
                description:
                  type: string
                  example: Big Estate Near the Indian Ocean
                  required:
                    - "false"
                country:
                  type: string
                  example: South Africa
                  required:
                    - "false"
      responses:
        '200':
          description: A JSON filtered array of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /searchAgency:
    post:
      summary: Return a list of all agencies linked to the destination id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                destination_id:
                  type: integer
                  format: int64
                  example: 42
                  required:
                    - "true"

      responses:
        "200":
          description: A JSON array of agencies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["WeKeepYourMoney","CheapAndUnsafe"]
  /contactAgency:
    post:
      summary: Return a form to fill to contact the selected agency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                destination_id:
                  type: integer
                  format: int64
                  example: 42
                  required:
                    - "true"
                agency_id:
                  type: integer
                  format: int64
                  example: 69
                  required:
                    - "true"

      responses:
        "200":
          description: PDF form 
          content:
            application/pdf:
              schema:
                type: string
                format: binary
  /agency/{agencyId}:
    get:
      summary: Return the coordinates of the Agency
      parameters:
        - name: agencyId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of agency information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                    format: int64
                    example: 42
                  name:
                    type: string
                    example: "WeKeepYourMoney"
                  email:
                    type: string
                    example: wekeepyourmoney@gmail.com
                  phone:
                    type: integer
                    format: int64
                    example: 324871937
                  localization:
                    type: string
                    example: wall street n°8
    delete:
      summary: Deletes an agency
      parameters:
        - name: agencyId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Agency deleted
  /agency: 
    post:
      summary: add new agency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "WeKeepYourMoney"
                email:
                  type: string
                  example: wekeepyourmoney@gmail.com
                phone:
                  type: integer
                  format: int64
                  example: 324871937
                localization:
                  type: string
                  example: wall street n°8
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Agency added
  /links:
    post:
      summary: add new link between agency and destination
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                destination:
                  type: string
                  example: Annecy
                agency:
                  type: string
                  example: WeKeepYourMoney

      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Link created
  /links{linkId}:
    delete:
      summary: Deletes a link
      parameters:
        - name: linkId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Link deleted

